Repository AY2324S1-CS2103T-F08-2/tp, pull requests merged in 2023-10, with the labels that each got.

#63 updated AboutUs.md
  docs/AboutUs.md
Labels: documentation

#101 Edit DG
  docs/DeveloperGuide.md
Labels: priority.High

#104 Refactor Meeting Times to be optional
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/ConvertClientToLeadCommand.java
  src/main/java/seedu/address/logic/commands/ConvertLeadToClientCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddClientCommandParser.java
  src/main/java/seedu/address/logic/parser/AddLeadCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Client.java
  src/main/java/seedu/address/model/person/Lead.java
  src/main/java/seedu/address/model/person/MeetingTime.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ConvertClientToLeadCommandTest.java
  src/test/java/seedu/address/logic/commands/ConvertLeadToClientCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddLeadCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/ClientUtil.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/LeadUtil.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalLeads.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.Medium
